21.10.2020 10:25:11 Checking for system tray...
21.10.2020 10:25:12 Starting pgAdmin4 server...
21.10.2020 10:25:12 Creating server object, port:64517, key:c38b4e90-1851-4927-9132-641aef799a16, logfile:C:/Users/Paul/.pgAdmin4.427924103.log
21.10.2020 10:25:12 Python Path: C:/Program Files (x86)/pgAdmin 4/v4/venv/Lib/site-packages;C:/Program Files (x86)/pgAdmin 4/v4/venv/DLLs;C:/Program Files (x86)/pgAdmin 4/v4/venv/Lib
21.10.2020 10:25:12 Python Home: C:/Program Files (x86)/pgAdmin 4/v4/venv
21.10.2020 10:25:12 Initializing Python...
21.10.2020 10:25:12 Python initialized.
21.10.2020 10:25:12 Adding new additional path elements
21.10.2020 10:25:12 Redirecting stderr...
21.10.2020 10:25:12 stderr redirected successfully.
21.10.2020 10:25:12 Initializing server...
21.10.2020 10:25:12 Webapp Path: C:/Program Files (x86)/pgAdmin 4/v4/web/pgAdmin4.py
21.10.2020 10:25:12 Server initialized.
21.10.2020 10:25:12 Starting Server Thread...
21.10.2020 10:25:12 Open the application code and run it.
21.10.2020 10:25:12 Set the port number, key and force SERVER_MODE off
21.10.2020 10:25:12 PyRun_SimpleFile launching application server...
21.10.2020 10:25:13 Application Server URL: http://127.0.0.1:64517/?key=c38b4e90-1851-4927-9132-641aef799a16
21.10.2020 10:25:13 The server should be up, we'll attempt to connect and get a response. Ping the server
21.10.2020 10:25:50 Attempt to connect one more time in case of a long network timeout while looping
21.10.2020 10:25:50 Everything works fine, successfully started pgAdmin4.
